name = "ocevave3"
compatibility_date = "2026-01-27"
pages_build_output_dir = "./dist"

compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "ocevave-production"
database_id = "d3e2fba5-2acd-4a78-a125-d4cf5ee81079"

[[r2_buckets]]
binding = "R2"
bucket_name = "ocevave"

